
export const HOME_HIGHLIGHT_LOADED = 'HOME_HIGHLIGHT_LOADED';

// Book Review Types
export const GET_FIRST_PAGE_BOOK_REVIEWS = 'GET_FIRST_PAGE_BOOK_REVIEWS';
export const GET_BOOK_REVIEW_DETAILS = 'GET_BOOK_REVIEW_DETAILS';
export const GET_EDIT_BOOK_REVIEW_DETAILS = 'GET_EDIT_BOOK_REVIEW_DETAILS';
export const ADMIN_BOOK_REVIEW_LOADED = 'ADMIN_BOOK_REVIEW_LOADED';
export const NUM_RECENT_BOOK_REVIEWS_LOADED = 'NUM_RECENT_BOOK_REVIEWS_LOADED';
export const NEXT_PAGE_BOOK_REVIEWS_LOADED = 'NEXT_PAGE_BOOK_REVIEWS_LOADED';

export const GET_FIRST_PAGE_PROJECTS = 'GET_FIRST_PAGE_PROJECTS';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
export const NEXT_PAGE_PROJECTS_LOADED = 'NEXT_PAGE_PROJECTS_LOADED';
export const GET_EDIT_PROJECT_DETAILS = 'GET_EDIT_PROJECT_DETAILS';
export const ADMIN_PROJECT_LOADED = 'ADMIN_PROJECT_LOADED';
export const NUM_RECENT_PROJECTS_LOADED = 'NUM_RECENT_PROJECTS_LOADED';
export const PROJECT_SPOTLIGHT_LOADED = 'PROJECT_SPOTLIGHT_LOADED';

export const GET_FIRST_PAGE_GUIDES = 'GET_FIRST_PAGE_GUIDES';
export const NEXT_PAGE_GUIDES_LOADED = 'NEXT_PAGE_GUIDES_LOADED';
export const GET_GUIDE_DETAILS = 'GET_GUIDE_DETAILS';
export const GET_EDIT_GUIDE_DETAILS = 'GET_EDIT_GUIDE_DETAILS';
export const ADMIN_GUIDE_LOADED = 'ADMIN_GUIDE_LOADED';
export const NUM_RECENT_GUIDES_LOADED = 'NUM_RECENT_GUIDES_LOADED';

export const GET_FIRST_PAGE_MONTHLY_FIVES = 'GET_FIRST_PAGE_MONTHLY_FIVES';
export const NEXT_PAGE_MONTHLY_FIVES_LOADED = 'NEXT_PAGE_MONTHLY_FIVES_LOADED';
export const GET_MONTHLY_FIVE_DETAILS = 'GET_MONTHLY_FIVE_DETAILS';
export const GET_EDIT_MONTHLY_FIVE_DETAILS = 'GET_EDIT_MONTHLY_FIVE_DETAILS';
export const ADMIN_MONTHLY_FIVE_LOADED = 'ADMIN_MONTHLY_FIVE_LOADED';
export const NUM_RECENT_MONTHLY_FIVES_LOADED = 'NUM_RECENT_MONTHLY_FIVES_LOADED';

export const GET_FIRST_PAGE_EVENTS = 'GET_FIRST_PAGE_EVENTS';
export const NEXT_PAGE_EVENTS_LOADED = 'NEXT_PAGE_EVENTS_LOADED';
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
export const GET_EDIT_EVENT_DETAILS = 'GET_EDIT_EVENT_DETAILS';
export const ADMIN_EVENT_LOADED = 'ADMIN_EVENT_LOADED';
export const NUM_RECENT_EVENTS_LOADED = 'NUM_RECENT_EVENTS_LOADED';

export const GET_FIRST_PAGE_BLOGS = 'GET_FIRST_PAGE_BLOGS';
export const NEXT_PAGE_BLOGS_LOADED = 'NEXT_PAGE_BLOGS_LOADED';
export const GET_BLOG_DETAILS = 'GET_BLOG_DETAILS';
export const GET_EDIT_BLOG_DETAILS = 'GET_EDIT_BLOG_DETAILS';
export const ADMIN_BLOG_LOADED = 'ADMIN_BLOG_LOADED';
export const NUM_RECENT_BLOGS_LOADED = 'NUM_RECENT_BLOGS_LOADED';

export const SET_USER = 'SET_USER';
