
// Book Review Types
export const GET_FIRST_PAGE_BOOK_REVIEWS = 'GET_FIRST_PAGE_BOOK_REVIEWS';
export const GET_BOOK_REVIEW_DETAILS = 'GET_BOOK_REVIEW_DETAILS';

export const GET_FIRST_PAGE_PROJECTS = 'GET_FIRST_PAGE_PROJECTS';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
