
// Book Review Types
export const GET_FIRST_PAGE_BOOK_REVIEWS = 'GET_FIRST_PAGE_BOOK_REVIEWS';
export const GET_BOOK_REVIEW_DETAILS = 'GET_BOOK_REVIEW_DETAILS';
export const GET_EDIT_BOOK_REVIEW_DETAILS = 'GET_EDIT_BOOK_REVIEW_DETAILS';
export const ADMIN_BOOK_REVIEW_LOADED = 'ADMIN_BOOK_REVIEW_LOADED';
export const NUM_RECENT_BOOK_REVIEWS_LOADED = 'NUM_RECENT_BOOK_REVIEWS_LOADED';

export const GET_FIRST_PAGE_PROJECTS = 'GET_FIRST_PAGE_PROJECTS';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
export const NEXT_PAGE_PROJECTS_LOADED = 'NEXT_PAGE_PROJECTS_LOADED';
export const GET_EDIT_PROJECT_DETAILS = 'GET_EDIT_PROJECT_DETAILS';
export const ADMIN_PROJECT_LOADED = 'ADMIN_PROJECT_LOADED';
export const NUM_RECENT_PROJECTS_LOADED = 'NUM_RECENT_PROJECTS_LOADED';
export const PROJECT_SPOTLIGHT_LOADED = 'PROJECT_SPOTLIGHT_LOADED';

export const GET_FIRST_PAGE_GUIDES = 'GET_FIRST_PAGE_GUIDES';
export const NEXT_PAGE_GUIDES_LOADED = 'NEXT_PAGE_GUIDES_LOADED';
export const GET_GUIDE_DETAILS = 'GET_GUIDE_DETAILS';
export const GET_EDIT_GUIDE_DETAILS = 'GET_EDIT_GUIDE_DETAILS';
export const ADMIN_GUIDE_LOADED = 'ADMIN_GUIDE_LOADED';
export const NUM_RECENT_GUIDES_LOADED = 'NUM_RECENT_GUIDES_LOADED';

export const SET_USER = 'SET_USER';
